### ISSUE TITLE
Usage example?

### ISSUE THREAD

**Issue by laanwj** [jeandudey/rust-bitcoin-rpc#4]
I was looking for example code on how to use `bitcoind` from Rust and stumbled on this repository.

This library looks promising, but there seems to be no documentation nor example! Or am I missing something?

**Comment by jeandudey** [comment]
Hi! @laanwj, this library is still a WIP and only some RPC calls are implemented, I'd recommend you to use the crate directly from the repository and not the version at crates.io (it's outdated a lot), like this:

```toml
[dependencies.bitcoin-rpc]
git = "https://github.com/jeandudey/rust-bitcoin-rpc/"
```

I know it doesn't has too much documentation, but I'll try to solve this when I can. However here is a simple overview of how to use it.

```rust
extern crate bitcoin_rpc;
extern crate bitcoin_rpc_json;

use bitcoin_rpc_json::mining::EstimateMode;

fn main() {
    let url = "http://localhost:18332".to_string();
    // The two None`s are for user/pass authentication.
    let client = bitcoin_rpc::BitcoinRpc::new(url, None, None);
    
    let response = client.estimatesmartfee(6, EstimateMode::Economical)
        .expect("couldn't call "estimatesmartfee" RPC");

    println!("{:?}", response);
}
```

I'll leave this issue open until I enable documentation generation in CI, and replace the documentation link to docs.rs.

**Comment by laanwj** [comment]
thank you!

trying your example gives me the following error:
```
   Compiling bitcoinrpctest v0.1.0 (file:///home/user/projects/bitcoinrpctest)
error[E0463]: can't find crate for `bitcoin_rpc_json`
 --> src/main.rs:2:1
  |
2 | extern crate bitcoin_rpc_json;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: Could not compile `bitcoinrpctest`.

To learn more, run the command again with --verbose.
```
I think I'm missing a dependency in `Cargo.toml`.

**Comment by laanwj** [comment]
This seems to have done it:
```
[dependencies.bitcoin-rpc]
git = "https://github.com/jeandudey/rust-bitcoin-rpc/"

[dependencies.bitcoin-rpc-json]
git = "https://github.com/jeandudey/rust-bitcoin-rpc/"
```

**Comment by jeandudey** [comment]
> I'll leave this issue open until I enable documentation generation in CI, and replace the documentation link to docs.rs.

I think this is going to take some time, Travis CI has banned my account for the moment.

**Comment by laanwj** [comment]
Got it to compile! 
it does complain about missing either `feerate` or `errors`, but that's a wholly different issue I think;
```bash
$ ./bitcoinrpctest 
thread 'main' panicked at 'couldn't call 'estimatesmartfee' RPC: Error { kind: Json(missing field `feerate`)

Response format is invalid }', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
```bash
$ ./bitcoinrpctest 
thread 'main' panicked at 'couldn't call 'estimatesmartfee' RPC: Error { kind: Json(missing field `errors`)

Response format is invalid }', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by jeandudey** [comment]
I think I've got it in the last commit, 
try  "cargo update" and build again

**Comment by laanwj** [comment]
yep that worked
```
$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.12s
     Running `target/debug/bitcoinrpctest`
EstimateSmartFee { feerate: Some(Json(Number("0.00002574"))), errors: None, blocks: 6 }
```
